// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_vQGlltii9To1tUW65bEg-noQc1OlQp0',
    appId: '1:521279889922:web:d06abaeb60886c93437d1b',
    messagingSenderId: '521279889922',
    projectId: 'carwash-7af73',
    authDomain: 'carwash-7af73.firebaseapp.com',
    storageBucket: 'carwash-7af73.firebasestorage.app',
    measurementId: 'G-S0F5W97FTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMtw3ZOkpAnlHqQaDihsFCCd8h5kHm8Hc',
    appId: '1:521279889922:android:4abffcd2b850dd43437d1b',
    messagingSenderId: '521279889922',
    projectId: 'carwash-7af73',
    storageBucket: 'carwash-7af73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj6N4pg8KdDi5-JVZMYJHOOBS7xuLsM-Y',
    appId: '1:521279889922:ios:63c686a5e2ec9233437d1b',
    messagingSenderId: '521279889922',
    projectId: 'carwash-7af73',
    storageBucket: 'carwash-7af73.firebasestorage.app',
    iosBundleId: 'com.example.moclienapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj6N4pg8KdDi5-JVZMYJHOOBS7xuLsM-Y',
    appId: '1:521279889922:ios:63c686a5e2ec9233437d1b',
    messagingSenderId: '521279889922',
    projectId: 'carwash-7af73',
    storageBucket: 'carwash-7af73.firebasestorage.app',
    iosBundleId: 'com.example.moclienapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_vQGlltii9To1tUW65bEg-noQc1OlQp0',
    appId: '1:521279889922:web:c57bd548404291c9437d1b',
    messagingSenderId: '521279889922',
    projectId: 'carwash-7af73',
    authDomain: 'carwash-7af73.firebaseapp.com',
    storageBucket: 'carwash-7af73.firebasestorage.app',
    measurementId: 'G-KFTKEN1KRQ',
  );
}